#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
REDIRECT_301="\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=lMJvDi0KNlM;\n\t}\n"

sudo touch /var/www/html/error_404_.html
echo "Ceci n'est pas une page" > /var/www/html/error_404_.html
NOTFOUND_404="\terror_page 404 /error_404_.html;\n\\tlocation = /error_404_.html {\n\t\tinternal;\n\t}\n"

PATTERN="server_name _;"
STRINGS="$PATTERN\n\n$REDIRECT_301\n$NOTFOUND_404"

sudo sed -i "s@$PATTERN@$STRINGS@" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
