#!/usr/bin/env bash
# Configures load balancer

apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy=2.0.\*
sed -i "$ a frontend load_balancer\n    bind *:80\n    mode http\n    default_backend web_servers\nbackend web_servers\n    balance roundrobin\n    server web-01 34.75.76.211:80 check\n    server web-02 3.90.215.119:80 check" /etc/haproxy/haproxy.cfg
service haproxy start
