#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -uroot -p"$1" --all-databases > backup.sql 2> /dev/null
tar -czf "$(date +%d-%m-%Y.tar.gz)" backup.sql
