#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s

sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep nginx | head -n1)"
