#!/usr/bin/env bash
# displays "To infinity and beyond" indefinitely and "I am invincible!!!"" when receiving a SIGTERM.

while true
do
	trap 'echo "I am invincible!!!"' SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
