#!/usr/bin/env bash
#displays "Holberton School" 10 times and show "Hi" in 9th iteration.
n=0
while [ $n -lt 11 ]
do
    if [ $n -eq 9 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    n=$(( n+1 ))
done
