#!/usr/bin/env bash
# display "bad luck" and "good luck" for the 4th and 8th iteration.
n=1
while [ $n -lt 11 ]
do
    if [ $n = 4 ]
    then
        echo "bad luck"
    elif [ $n = 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    n=$(( n+=1 ))
done
