#!/usr/bin/env bash
#displays numbers from 1 to 20
n=1
while [ $n -lt 21 ]
do
    echo $n
    case $n in

        4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
    esac
    n=$(( n+=1 ))
done
